[all]
# node1 ansible_host=127.0.0.1 ansible_connection=local
node1 ansible_host=192.168.169.170 ip=192.168.169.170 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/k8s_multipass_rsa ansible_python_interpreter=/usr/bin/python3

[kube_control_plane]
node1

[etcd]
node1

[kube_node]
node1

[k8s_cluster:children]
kube_control_plane
kube_node